import Link from "next/link";
import { getSession } from "@/server/auth/session";
import { prisma } from "@/server/db/prisma";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { PlusCircle, FileText, Clock, CheckCircle2, XCircle, Loader2 } from "lucide-react";

export const dynamic = "force-dynamic";

const STATUS_BADGE: Record<string, { label: string; icon: React.ReactNode; className: string }> = {
  PENDING: { label: "Pending", icon: <Clock className="h-3 w-3" />, className: "bg-muted text-muted-foreground" },
  RUNNING: { label: "Running", icon: <Loader2 className="h-3 w-3 animate-spin" />, className: "bg-blue-100 text-blue-800" },
  COMPLETE: { label: "Complete", icon: <CheckCircle2 className="h-3 w-3" />, className: "bg-emerald-100 text-emerald-800" },
  FAILED: { label: "Failed", icon: <XCircle className="h-3 w-3" />, className: "bg-red-100 text-red-800" },
};

const TYPE_COLORS: Record<string, string> = {
  WBR: "bg-blue-100 text-blue-800",
  MBR: "bg-purple-100 text-purple-800",
  QBR: "bg-emerald-100 text-emerald-800",
};

export default async function ReviewsListPage() {
  const session = await getSession();
  const userId = session?.user?.id;
  const isAdmin = false; // TODO: check role from DB if needed

  const reviews = await prisma.businessReview.findMany({
    where: userId && !isAdmin ? { requestedByUserId: userId } : undefined,
    orderBy: { createdAt: "desc" },
    take: 50,
    include: { requestedBy: { select: { name: true, email: true } } },
  });

  return (
    <div className="space-y-6">
      <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h1 className="text-2xl font-semibold text-foreground">Business Reviews</h1>
          <p className="text-sm text-muted-foreground">
            WBR, MBR, and QBR documents generated from live Jira and Adobe Analytics data
          </p>
        </div>
        <Button asChild>
          <Link href="/reviews/new">
            <PlusCircle className="h-4 w-4 mr-2" />
            New Review
          </Link>
        </Button>
      </div>

      <Card>
        <CardHeader>
          <CardTitle className="text-base font-medium">
            Recent Reviews ({reviews.length})
          </CardTitle>
        </CardHeader>
        <CardContent className="p-0">
          {reviews.length === 0 ? (
            <div className="flex flex-col items-center gap-3 py-16 text-center">
              <FileText className="h-10 w-10 text-muted-foreground opacity-40" />
              <p className="text-sm font-medium text-foreground">No reviews yet</p>
              <p className="text-sm text-muted-foreground">Generate your first WBR, MBR, or QBR</p>
              <Button asChild size="sm" className="mt-2">
                <Link href="/reviews/new">Generate Review</Link>
              </Button>
            </div>
          ) : (
            <Table>
              <TableHeader>
                <TableRow className="bg-muted/50">
                  <TableHead>Type</TableHead>
                  <TableHead>Period</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead>Generated By</TableHead>
                  <TableHead>Created</TableHead>
                  <TableHead className="w-[80px]"></TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {reviews.map((r) => {
                  const statusInfo = STATUS_BADGE[r.status] ?? STATUS_BADGE.PENDING;
                  return (
                    <TableRow key={r.id} className="hover:bg-muted/30">
                      <TableCell>
                        <Badge className={TYPE_COLORS[r.type] ?? ""}>{r.type}</Badge>
                      </TableCell>
                      <TableCell className="text-sm">
                        {r.dateStart.toLocaleDateString("en-US", { month: "short", day: "numeric" })}
                        {" – "}
                        {r.dateEnd.toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}
                      </TableCell>
                      <TableCell>
                        <span
                          className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-0.5 text-xs font-medium ${statusInfo.className}`}
                        >
                          {statusInfo.icon}
                          {statusInfo.label}
                        </span>
                      </TableCell>
                      <TableCell className="text-sm text-muted-foreground">
                        {r.requestedBy.name ?? r.requestedBy.email}
                      </TableCell>
                      <TableCell className="text-sm text-muted-foreground">
                        {r.createdAt.toLocaleDateString()}
                      </TableCell>
                      <TableCell>
                        <Button variant="ghost" size="sm" asChild>
                          <Link href={`/reviews/${r.id}`}>View</Link>
                        </Button>
                      </TableCell>
                    </TableRow>
                  );
                })}
              </TableBody>
            </Table>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
