import type { 
  Initiative, 
  Owner, 
  Activity, 
  WorkflowStage, 
  NotificationRule,
  ApprovalMatrix,
  JiraMapping 
} from "./types";

export const owners: Owner[] = [
  { id: "1", name: "Sarah Chen", email: "sarah.chen@company.com", role: "Product Manager" },
  { id: "2", name: "Marcus Johnson", email: "marcus.j@company.com", role: "Engineering Lead" },
  { id: "3", name: "Emily Rodriguez", email: "emily.r@company.com", role: "Product Director" },
  { id: "4", name: "David Kim", email: "david.kim@company.com", role: "Tech Lead" },
  { id: "5", name: "Rachel Patel", email: "rachel.p@company.com", role: "Design Lead" },
  { id: "6", name: "James Wilson", email: "james.w@company.com", role: "VP Engineering" },
];

export const initiatives: Initiative[] = [
  {
    id: "INI-001",
    title: "Real-time Collaboration Engine",
    description: "Build a real-time collaboration system for document editing with conflict resolution",
    workstream: "Platform",
    stage: "Development",
    status: "In Progress",
    owner: owners[0],
    quarter: "Q2",
    year: 2024,
    risk: "Medium",
    priority: 1,
    createdAt: "2024-01-15",
    updatedAt: "2024-03-20",
    targetDate: "2024-06-30",
    problemStatement: "Users cannot collaborate in real-time on documents, leading to version conflicts and reduced productivity.",
    goals: ["Enable simultaneous editing", "Reduce merge conflicts by 90%", "Support offline mode"],
    kpis: [
      { id: "k1", name: "Concurrent Users", baseline: "1", target: "100", current: "45", unit: "users" },
      { id: "k2", name: "Sync Latency", baseline: "5000", target: "200", current: "350", unit: "ms" },
    ],
    dependencies: [
      { id: "d1", title: "WebSocket Infrastructure", type: "Internal", status: "Resolved" },
      { id: "d2", title: "Auth Service v2", type: "Internal", status: "Pending" },
    ],
    risks: [
      { id: "r1", description: "Performance at scale", likelihood: "Medium", impact: "High", mitigation: "Load testing planned" },
    ],
    approvals: [
      { id: "a1", type: "Technical Review", approver: owners[1], status: "Approved", reviewedAt: "2024-02-01" },
      { id: "a2", type: "Product Approval", approver: owners[2], status: "Approved", reviewedAt: "2024-02-05" },
    ],
    jiraKey: "PLAT-1234",
    impactScore: 85,
    effortScore: 70,
  },
  {
    id: "INI-002",
    title: "Enterprise SSO Integration",
    description: "Implement SAML and OIDC support for enterprise customers",
    workstream: "Enterprise",
    stage: "Testing",
    status: "In Progress",
    owner: owners[3],
    quarter: "Q2",
    year: 2024,
    risk: "Low",
    priority: 2,
    createdAt: "2024-02-01",
    updatedAt: "2024-03-18",
    targetDate: "2024-05-15",
    jiraKey: "ENT-567",
    impactScore: 90,
    effortScore: 50,
  },
  {
    id: "INI-003",
    title: "Mobile App Redesign",
    description: "Complete redesign of the mobile app with new design system",
    workstream: "Mobile",
    stage: "Design",
    status: "Blocked",
    owner: owners[4],
    quarter: "Q2",
    year: 2024,
    risk: "High",
    priority: 3,
    createdAt: "2024-01-20",
    updatedAt: "2024-03-15",
    targetDate: "2024-07-30",
    jiraKey: "MOB-890",
    impactScore: 75,
    effortScore: 85,
  },
  {
    id: "INI-004",
    title: "AI-Powered Search",
    description: "Implement semantic search using LLM embeddings",
    workstream: "Platform",
    stage: "Discovery",
    status: "Pending Approval",
    owner: owners[0],
    quarter: "Q3",
    year: 2024,
    risk: "High",
    priority: 4,
    createdAt: "2024-03-01",
    updatedAt: "2024-03-19",
    targetDate: "2024-09-30",
    approvals: [
      { id: "a3", type: "Technical Review", approver: owners[1], status: "Pending", checklist: [
        { id: "c1", label: "Architecture reviewed", completed: true },
        { id: "c2", label: "Security assessment", completed: false },
        { id: "c3", label: "Cost analysis", completed: true },
      ]},
    ],
    impactScore: 95,
    effortScore: 90,
  },
  {
    id: "INI-005",
    title: "Analytics Dashboard v2",
    description: "Rebuild analytics with real-time metrics and custom reports",
    workstream: "Data & Analytics",
    stage: "Definition",
    status: "Pending Approval",
    owner: owners[2],
    quarter: "Q2",
    year: 2024,
    risk: "Medium",
    priority: 5,
    createdAt: "2024-02-15",
    updatedAt: "2024-03-17",
    targetDate: "2024-06-15",
    approvals: [
      { id: "a4", type: "Product Approval", approver: owners[5], status: "Pending", checklist: [
        { id: "c4", label: "Business case reviewed", completed: true },
        { id: "c5", label: "Resource allocation confirmed", completed: false },
      ]},
    ],
    impactScore: 80,
    effortScore: 65,
  },
  {
    id: "INI-006",
    title: "Infrastructure Migration to K8s",
    description: "Migrate legacy services to Kubernetes",
    workstream: "Infrastructure",
    stage: "Development",
    status: "In Progress",
    owner: owners[1],
    quarter: "Q2",
    year: 2024,
    risk: "Critical",
    priority: 1,
    createdAt: "2024-01-05",
    updatedAt: "2024-03-20",
    targetDate: "2024-04-30",
    jiraKey: "INFRA-234",
    impactScore: 70,
    effortScore: 95,
  },
  {
    id: "INI-007",
    title: "Growth Experimentation Platform",
    description: "Build A/B testing and feature flagging infrastructure",
    workstream: "Growth",
    stage: "Release",
    status: "Approved",
    owner: owners[3],
    quarter: "Q1",
    year: 2024,
    risk: "Low",
    priority: 2,
    createdAt: "2023-11-01",
    updatedAt: "2024-03-10",
    targetDate: "2024-03-31",
    jiraKey: "GROW-123",
    impactScore: 88,
    effortScore: 55,
  },
  {
    id: "INI-008",
    title: "Payment System Overhaul",
    description: "Modernize payment processing with multi-currency support",
    workstream: "Enterprise",
    stage: "Post-Release",
    status: "Completed",
    owner: owners[0],
    quarter: "Q1",
    year: 2024,
    risk: "Low",
    priority: 1,
    createdAt: "2023-09-01",
    updatedAt: "2024-02-28",
    targetDate: "2024-02-28",
    jiraKey: "ENT-456",
    impactScore: 92,
    effortScore: 80,
  },
  {
    id: "INI-009",
    title: "Customer Portal Refresh",
    description: "Update customer-facing portal with modern UX",
    workstream: "Growth",
    stage: "Design",
    status: "On Hold",
    owner: owners[4],
    quarter: "Q3",
    year: 2024,
    risk: "Medium",
    priority: 6,
    createdAt: "2024-02-20",
    updatedAt: "2024-03-05",
    targetDate: "2024-08-30",
    impactScore: 65,
    effortScore: 60,
  },
  {
    id: "INI-010",
    title: "API Rate Limiting v2",
    description: "Implement distributed rate limiting with Redis",
    workstream: "Infrastructure",
    stage: "Testing",
    status: "In Progress",
    owner: owners[1],
    quarter: "Q2",
    year: 2024,
    risk: "Low",
    priority: 4,
    createdAt: "2024-02-10",
    updatedAt: "2024-03-18",
    targetDate: "2024-04-15",
    jiraKey: "INFRA-567",
    impactScore: 60,
    effortScore: 40,
  },
];

export const activities: Activity[] = [
  {
    id: "act-1",
    initiativeId: "INI-001",
    type: "status_change",
    description: "Status changed from Approved to In Progress",
    user: owners[0],
    timestamp: "2024-03-20T14:30:00Z",
  },
  {
    id: "act-2",
    initiativeId: "INI-001",
    type: "comment",
    description: "Sprint planning completed. Development starting next week.",
    user: owners[1],
    timestamp: "2024-03-19T10:15:00Z",
  },
  {
    id: "act-3",
    initiativeId: "INI-001",
    type: "approval",
    description: "Technical Review approved by Marcus Johnson",
    user: owners[1],
    timestamp: "2024-02-01T09:00:00Z",
  },
  {
    id: "act-4",
    initiativeId: "INI-003",
    type: "status_change",
    description: "Status changed to Blocked - waiting on design resources",
    user: owners[4],
    timestamp: "2024-03-15T16:45:00Z",
  },
];

export const workflowStages: WorkflowStage[] = [
  { id: "ws-1", name: "Discovery", order: 1, color: "#94a3b8", requiredApprovals: [] },
  { id: "ws-2", name: "Definition", order: 2, color: "#60a5fa", requiredApprovals: ["Product Approval"] },
  { id: "ws-3", name: "Design", order: 3, color: "#a78bfa", requiredApprovals: ["Design Review"] },
  { id: "ws-4", name: "Development", order: 4, color: "#fbbf24", requiredApprovals: ["Technical Review", "Security Review"] },
  { id: "ws-5", name: "Testing", order: 5, color: "#f97316", requiredApprovals: ["QA Sign-off"] },
  { id: "ws-6", name: "Release", order: 6, color: "#22c55e", requiredApprovals: ["Release Approval"] },
  { id: "ws-7", name: "Post-Release", order: 7, color: "#14b8a6", requiredApprovals: [] },
];

export const notificationRules: NotificationRule[] = [
  { id: "nr-1", name: "Initiative Status Change", trigger: "status_change", recipients: ["owner", "stakeholders"], enabled: true },
  { id: "nr-2", name: "Approval Request", trigger: "approval_requested", recipients: ["approvers"], enabled: true },
  { id: "nr-3", name: "Risk Level Escalation", trigger: "risk_escalation", recipients: ["owner", "leadership"], enabled: true },
  { id: "nr-4", name: "Target Date Approaching", trigger: "deadline_approaching", recipients: ["owner", "team"], enabled: false },
];

export const approvalMatrix: ApprovalMatrix[] = [
  { id: "am-1", stage: "Definition", approverRoles: ["Product Director", "VP Product"], requiredCount: 1 },
  { id: "am-2", stage: "Development", approverRoles: ["Engineering Lead", "Tech Lead"], requiredCount: 2 },
  { id: "am-3", stage: "Release", approverRoles: ["VP Engineering", "Product Director"], requiredCount: 2 },
];

export const jiraMappings: JiraMapping[] = [
  { id: "jm-1", initiativeField: "title", jiraField: "summary", syncDirection: "push" },
  { id: "jm-2", initiativeField: "description", jiraField: "description", syncDirection: "both" },
  { id: "jm-3", initiativeField: "status", jiraField: "status", syncDirection: "pull" },
  { id: "jm-4", initiativeField: "priority", jiraField: "priority", syncDirection: "push" },
];

export const checklistTemplates = [
  {
    id: "ct-1",
    name: "Technical Review Checklist",
    items: [
      "Architecture reviewed and approved",
      "Security assessment completed",
      "Performance requirements defined",
      "Cost analysis reviewed",
      "Dependencies identified",
    ],
  },
  {
    id: "ct-2",
    name: "Product Approval Checklist",
    items: [
      "Business case validated",
      "Success metrics defined",
      "User research completed",
      "Resource allocation confirmed",
      "Timeline approved",
    ],
  },
  {
    id: "ct-3",
    name: "Release Checklist",
    items: [
      "All tests passing",
      "Documentation updated",
      "Rollback plan in place",
      "Monitoring configured",
      "Stakeholders notified",
    ],
  },
];
